[target.aarch64-linux-android]
linker = "clang"
rustflags = [
    "-C", "link-arg=-L/data/data/com.termux/files/home/transcribe_v2/jniLibs/arm64-v8a",
    "-C", "link-arg=-lonnxruntime",
    "-C", "link-arg=-llog",
    "-C", "link-arg=-lc++_shared"
]
